baseURL = "http://camptocamp.github.io/puppet-modules/"
title = "Puppet Modules"
languageCode = "en-us"
theme = "elate"

[params]

  #custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Camptocamp"
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Camptocamp's Puppet Modules"
    intro = "<i class='icon-home'></i>Install"
    #work = "<i class='icon-camera'></i>Screenshots"
    #testimonials = "<i class='icon-bubbles'></i>Testimonials"
    #services = "<i class='icon-star'></i>Features"
    about = "<i class='icon-bulb'></i>Other projects"
    contact = "<i class='icon-envelope'></i> Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order

  # Hero section
  [params.hero]
    title = "![Puppet](images/puppet.png)<p>Camptocamp's Puppet Modules</p>"
    subtitle = ""

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Install"
    description = '''
```shell
$ puppet module install camptocamp/<module_name>
```
'''
    icon = "icon-rocket"


  [[params.intro.item]]
    title = "Forge Modules"
    description = '''
Camptocamp maintains tens of modules on the Puppet Forge

<svg id="modules_bubbles" width="800" height="800" font-family="sans-serif" font-size="10" text-anchor="middle">
<image id="loading" xlink:href="loading_spinner.gif" x="350" y="350" height="100px" width="100px" />
</svg>

<script src="https://d3js.org/d3.v4.min.js"></script>
<script src="js/modules_bubbles.js"></script>
'''
    icon = "icon-bulb"

  # About section
  [params.about]
    enable = true
    title = "Other projects"
    description = "We love to contribute Open Source projects at Camptocamp.<br /> Here is a list of some of our most useful tools"

    [[params.about.item]]
      name = "Terraboard"
      position = "A Web dashboard to inspect and query Terraform states"
      description = ""
      img = "terraboard.png"
      alt = "Terraboard"
      social = [
        ["icon-globe", "https://camptocamp.github.io/terraboard"],
        ["icon-github", "https://github.com/camptocamp/terraboard"]
      ]

    [[params.about.item]]
      name = "Bivac"
      position = "Backup Interface for Volumes Attached to Containers"
      description = ""
      img = "bivac.png"
      alt = "Bivac"
      social = [
        ["icon-globe", "https://camptocamp.github.io/bivac"],
        ["icon-github", "https://github.com/camptocamp/bivac"]
      ]

  # Contact section
  [params.contact]
    enable = true
    form = false
    title = "Contact us!"
    description = "Are you missing features? Would you like consulting, training or other services? Contact us at [info@camptocamp.com](mailto:info@camptocamp.com?subject=Terraboard)!"

  # Footer section
  [params.footer]
    enable = true
    copyright = '[![Camptocamp](images/camptocamp.png)](https://www.camptocamp.com)'
    links = [
        ["icon-globe", "https://www.camptocamp.com"],
        ["icon-twitter", "https://twitter.com/camptocamp"],
        ["icon-github", "https://github.com/camptocamp"]
      ]
